# Generated by Django 4.0.8 on 2024-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_newsandevents_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
