# Generated by Django 4.0.8 on 2024-10-17 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_remove_parent_student_student_parent'),
        ('course', '0007_alter_upload_file_alter_uploadvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.IntegerField(null=True)),
                ('class_session', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True, unique=True)),
                ('end_time', models.TimeField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='course',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='Valid Files: pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip', upload_to='class_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip', 'txt'])]),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retake', models.BooleanField(default=False)),
                ('class_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_class', to='course.class')),
                ('course_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_course', to='course.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.timeslot'),
        ),
        migrations.AddField(
            model_name='upload',
            name='class_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='class_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.class'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'class_enrolled', 'course_enrolled'), name='unique_student_course_class'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('session', 'course', 'time_slot'), name='unique_session_course_timeslot'),
        ),
    ]
